name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-docs-verify.yml@main

  docgen:
      uses: justland/.github/.github/workflows/pnpm-docs.yml@main
      needs: code
